/**
 * Instruction Database
 */ 

 #include "Instruction_add.hh"
 #include "Instruction_sub.hh"
 #include "Instruction_mul.hh"
 #include "Instruction_ifL.hh"
 #include "Instruction_ifl.hh"
 #include "Instruction_ife.hh"
 #include "Instruction_ieL.hh"
 #include "Instruction_iel.hh"
 #include "Instruction_iee.hh"
 #include "Instruction_jmp.hh"
 #include "Instruction_put.hh"
 #include "Instruction_crt.hh"
 #include "Instruction_cra.hh"
 #include "Instruction_del.hh"
 #include "Instruction_ret.hh"
 #include "Instruction_wat.hh"
 #include "Instruction_brk.hh"
 #include "Instruction_ebk.hh"
 #include "Instruction_cln.hh"
 #include "Instruction_DST.hh"
 #include "Instruction_SIM.hh"
 #include "Instruction_GTA.hh"
 #include "Instruction_GAP.hh"